// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerXmlToFile(arg1) {
  return window['go']['main']['App']['AddServerXmlToFile'](arg1);
}

export function DecodeFile(arg1) {
  return window['go']['main']['App']['DecodeFile'](arg1);
}

export function DeleteTmpFiles() {
  return window['go']['main']['App']['DeleteTmpFiles']();
}

export function FileUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileUpload'](arg1, arg2, arg3);
}

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}

export function ReadRepositoryListFile() {
  return window['go']['main']['App']['ReadRepositoryListFile']();
}

export function WriteRepositoryListFile(arg1) {
  return window['go']['main']['App']['WriteRepositoryListFile'](arg1);
}
