// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServerXmlToFile(arg1:main.Repository):Promise<void>;

export function DecodeFile(arg1:main.UploadFileData):Promise<void>;

export function DeleteTmpFiles():Promise<void>;

export function FileUpload(arg1:string,arg2:main.Repository,arg3:main.UploadFileData):Promise<void>;

export function Initialize():Promise<void>;

export function ReadRepositoryListFile():Promise<string>;

export function WriteRepositoryListFile(arg1:string):Promise<void>;
