name: Build and Release Wails App

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install Dependencies
        run: |
          echo "Install Wails CLI"
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "Install npm packages"
          npm install --prefix ./frontend
          echo "Install Wails Dependencies package"
          sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu jammy main"
          sudo apt-get update -y
          sudo apt-get install -y gcc libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build Application for Winddows/amd64
        run: |
          wails build -clean -platform windows/amd64
          mkdir -p build/bin/winamd64/config/
          cp -r build/bin/*.exe build/bin/winamd64/
          cp -r config/* build/bin/winamd64/config/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libsynchro-win-amd64
          path: build/bin/winamd64

      - name: Build Application for Winddows/arm64
        run: | 
          wails build -clean -platform windows/arm64
          mkdir -p build/bin/winarm64/config/
          cp -r build/bin/*.exe build/bin/winarm64/
          cp -r config/* build/bin/winarm64/config/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libsynchro-win-arm64
          path: build/bin/winarm64

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libsynchro-win-amd64
          path: build/bin/winamd64

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libsynchro-win-arm64
          path: build/bin/winarm64

      - name: Zip Windows amd64 Artifacts
        run: |
          cd $GITHUB_WORKSPACE/build/bin/winamd64
          zip -r libsynchro-win-amd64.zip ./
          ls -la

      - name: Zip Windows arm64 Artifacts
        run: |
          cd $GITHUB_WORKSPACE/build/bin/winarm64
          zip -r libsynchro-win-arm64.zip ./
          ls -la

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/winamd64/libsynchro-win-amd64.zip
            build/bin/winarm64/libsynchro-win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
